nginx:
  build: ./other/nginx/
  #image: dnmp_nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php-7.2:fpm-7.2
    - php-7.1:fpm-7.1
    - php-5.6:fpm-5.6

php-7.2:
  build: ./php/php-7.2/
  #image: dnmp_php-7.2:latest
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php-7.2/php.ini:/etc/php.ini:ro
    - ./conf/php-7.2/php-fpm.d/www.conf:/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm-7.2/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis
    - memcached:memcached


php-7.1:
  build: ./php/php-7.1/
  #image: dnmp_php-7.1:latest
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php-7.1/php.ini:/etc/php.ini:ro
    - ./conf/php-7.1/php-fpm.d/www.conf:/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm-7.1/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis
    - memcached:memcached
 
php-5.6:
  build: ./php/php-5.6/
  #image: dnmp_php-5.6:latest
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php-5.6/php.ini:/etc/php.ini:ro
    - ./conf/php-5.6/php-fpm.d/www.conf:/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm-5.6/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis 
    - memcached:memcached

mysql:
  build: ./other/mysql/
  #image: dnmp_mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"

redis:
  build: ./other/redis/
  #image: dnmp_redis:latest
  ports:
    - "6379:6379"
  volumes:
    - ./conf/redis/redis.conf:/usr/local/etc/redis.conf:ro

memcached:
  build: ./other/memcached/
  #image: dnmp_redis:latest
  ports:
    - "11211:11211"

